name: Build RyukGram IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and Inject Tweak into IPA
        uses: swaggyP36000/TweakInstaller-Action@main
        with:
          decrypted_ipa_url: "https://pub-db7fbc0a417349bdaaa75968ff2572cb.r2.dev/Instagram_latest_decrypted.ipa"
          tweak_type: "theos"
          sdk_version: "16.2"

      - name: Upload Clean IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RyukGram-Sideload-IPA
          path: main_output/*.ipa
